# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/background_removal.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'proto/background_removal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eproto/background_removal.proto\x12\x15\x62\x61\x63kground_removal.v1\"\x12\n\x10GetModelsRequest\"K\n\tModelInfo\x12\x13\n\x0bunique_name\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"E\n\x11GetModelsResponse\x12\x30\n\x06models\x18\x01 \x03(\x0b\x32 .background_removal.v1.ModelInfo\"<\n\x17RemoveBackgroundRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x12\n\nmodel_name\x18\x02 \x01(\t\"Y\n\x18RemoveBackgroundResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x1a\n\x12processing_time_ms\x18\x03 \x01(\x04\x32\xef\x01\n\x18\x42\x61\x63kgroundRemovalService\x12^\n\tGetModels\x12\'.background_removal.v1.GetModelsRequest\x1a(.background_removal.v1.GetModelsResponse\x12s\n\x10RemoveBackground\x12..background_removal.v1.RemoveBackgroundRequest\x1a/.background_removal.v1.RemoveBackgroundResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.background_removal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETMODELSREQUEST']._serialized_start=57
  _globals['_GETMODELSREQUEST']._serialized_end=75
  _globals['_MODELINFO']._serialized_start=77
  _globals['_MODELINFO']._serialized_end=152
  _globals['_GETMODELSRESPONSE']._serialized_start=154
  _globals['_GETMODELSRESPONSE']._serialized_end=223
  _globals['_REMOVEBACKGROUNDREQUEST']._serialized_start=225
  _globals['_REMOVEBACKGROUNDREQUEST']._serialized_end=285
  _globals['_REMOVEBACKGROUNDRESPONSE']._serialized_start=287
  _globals['_REMOVEBACKGROUNDRESPONSE']._serialized_end=376
  _globals['_BACKGROUNDREMOVALSERVICE']._serialized_start=379
  _globals['_BACKGROUNDREMOVALSERVICE']._serialized_end=618
# @@protoc_insertion_point(module_scope)
