# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/background_removal.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'proto/background_removal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eproto/background_removal.proto\x12\x15\x62\x61\x63kground_removal.v1\"\x12\n\x10GetModelsRequest\"C\n\tModelInfo\x12\x13\n\x0bunique_name\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"E\n\x11GetModelsResponse\x12\x30\n\x06models\x18\x01 \x03(\x0b\x32 .background_removal.v1.ModelInfo\"S\n\x11\x43learImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x19\n\x11model_unique_name\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\"p\n\x12\x43learImageResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12\x19\n\x11model_unique_name\x18\x03 \x01(\t\x12\x1a\n\x12processing_time_ms\x18\x04 \x01(\x04\x32\xdd\x01\n\x18\x42\x61\x63kgroundRemovalService\x12^\n\tGetModels\x12\'.background_removal.v1.GetModelsRequest\x1a(.background_removal.v1.GetModelsResponse\x12\x61\n\nClearImage\x12(.background_removal.v1.ClearImageRequest\x1a).background_removal.v1.ClearImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.background_removal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETMODELSREQUEST']._serialized_start=57
  _globals['_GETMODELSREQUEST']._serialized_end=75
  _globals['_MODELINFO']._serialized_start=77
  _globals['_MODELINFO']._serialized_end=144
  _globals['_GETMODELSRESPONSE']._serialized_start=146
  _globals['_GETMODELSRESPONSE']._serialized_end=215
  _globals['_CLEARIMAGEREQUEST']._serialized_start=217
  _globals['_CLEARIMAGEREQUEST']._serialized_end=300
  _globals['_CLEARIMAGERESPONSE']._serialized_start=302
  _globals['_CLEARIMAGERESPONSE']._serialized_end=414
  _globals['_BACKGROUNDREMOVALSERVICE']._serialized_start=417
  _globals['_BACKGROUNDREMOVALSERVICE']._serialized_end=638
# @@protoc_insertion_point(module_scope)
